# Either define individual jobs:
jobs:
  - energy: 5e16
    n_events: 20000
  - energy: 1e17
    n_events: 20000
  - energy: 5e17
    n_events: 20000
  - energy: 1e18
    n_events: 15000
  - energy: 5e18
    n_events: 15000
  - energy: 1e19
    n_events: 10000
  - energy: 5e19
    n_events: 10000
  - energy: 1e20
    n_events: 5000
  - energy: 5e20
    n_events: 5000

# OR define a range:
range:
  E_min: 5e16
  E_max: 1e20
  points_per_decade: 3
  range_type: log # "log" or "linear"
  n_events_max: 50000
  n_events_min: 10000
  decline_type: exponential
  decline_factor: 2

# Conda environment
conda_env: "envs/nuradio_env.yaml"
mode: range
